# Custom Language File for Launcher Customizer

[ejs.app]
title = "여름방학 초코고 大 운동회"

[ejs.landing]
mediaGitHubURL = "https://bj.afreecatv.com/moolchoco/post/127249043"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
screenshotsTooltip = "스크린샷"
mediaAfreecaTVURL = "https://bj.afreecatv.com/moolchoco/post/126972041"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/chocogo"
supportLink = "https://github.com/CustomLauncherLab/chocogo/issues"

[ejs.welcome]
welcomeHeader = "여름방학 초코고 大 운동회"
welcomeDescription = ""
welcomeDescCTA = ""
